spring.application.name=staff
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/stock}
spring.datasource.username=postgres
spring.datasource.password=p@ssword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
