spring.application.name=staff
spring.datasource.url=jdbc:postgresql://stock_db_ocau_user:bvX8sNlCSfdBRGska4cmIeadH5X5i3zb@dpg-dappgrbbc2fs73bjcfmg-a/stock_db_ocau
spring.datasource.username=stock_db_ocau_user
spring.datasource.password=bvX8sNlCSfdBRGska4cmIeadH5X5i3zb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
