spring.application.name=staff

server.port=8080

# แก้ไขบรรทัดนี้: ตัด stock_db_ocau_user:bvX8sNlCSfdBRGska4cmIeadH5X5i3zb@ ออก
spring.datasource.url=jdbc:postgresql://dpg-dappgrbbc2fs73bjcfmg-a.singapore-postgres.render.com/stock_db_ocau

spring.datasource.username=stock_db_ocau_user
spring.datasource.password=bvX8sNlCSfdBRGska4cmIeadH5X5i3zb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
